name: Node.js Package

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          version: "12"
          runtime: node@lts
          install: true

      - run: pnpm publish --no-git-checks
